services:
    website-backend:
        image: ghcr.io/opengovernance-io/website-service:v0.0.9
        container_name: website-service
        ports:
        - "8080:8080"
        environment:
          - SCHEMA_HTTP__ADDRESS=0.0.0.0:8080
          - SCHEMA_POSTGRES__HOST=postgres
          - SCHEMA_POSTGRES__PORT=5432
          - SCHEMA_POSTGRES__DB=website
          - SCHEMA_POSTGRES__USERNAME=website
          - SCHEMA_POSTGRES__PASSWORD=${PG_PASSWORD}
          - SCHEMA_POSTGRES_SSL_MODE=disable
        depends_on:
        - postgres
        networks:
        - og-network
        restart: always
    postgres:
        image: postgres:14
        container_name: postgres
        volumes:
          - pgdata:/var/lib/postgresql/data
        environment:
        - POSTGRES_USER=website
        - POSTGRES_PASSWORD=${PG_PASSWORD}
        - POSTGRES_DB=website
        networks:
        - og-network
        restart: always
volumes:
    pgdata:
        driver: local
        driver_opts:
          type: none
          device: "website-service/pgdata"
          o: bind

networks:
    og-network:
        driver: bridge