# config.yaml
database:
  host: "localhost"
  port: "5432"
  user: "crito"
  password: ""
  dbname: "json_loader"
  sslmode: "disable"

workerCount: 10                    # Number of concurrent workers